name: Dastardly Scan

on:
  push:
    branches: [master, main]

jobs:

  scan-with-dastardly:
    name: Scan with Dastardly
    runs-on: ubuntu-latest

    steps:    
      - name: Run Dastardly Scan
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: 'https://vulnerable-site.azurewebsites.net/'

      - name: Commands
        run: |
            ls
            pwd
          
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
         path: '**/dastardly-report.xml'

      - name: Publish Dastardly Scan Report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: 'Dastardly Scan Report'
          report_paths: '**/dastardly-report.xml'
